"""messing with dateTime

Revision ID: 156a5913d075
Revises: ec4da7ba1532
Create Date: 2024-05-06 11:10:49.188341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156a5913d075'
down_revision = 'ec4da7ba1532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
