"""users

Revision ID: 528dc40ce847
Revises: bb89041afbb7
Create Date: 2024-05-01 16:03:16.700314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528dc40ce847'
down_revision = 'bb89041afbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_test')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
