"""password hash

Revision ID: 6afe6381af08
Revises: 528dc40ce847
Create Date: 2024-05-02 14:39:01.947408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afe6381af08'
down_revision = '528dc40ce847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.TEXT(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
