"""time as a string

Revision ID: 8f310b1a0954
Revises: 156a5913d075
Create Date: 2024-05-06 11:15:18.707138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f310b1a0954'
down_revision = '156a5913d075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
